openhab-scripters/openhab-helper-libraries

README.md

It seems that EACH_MINUTE has been renamed to EVERY_MINUTE. Example file is correct, but the change has been missing in README.MD.

EACH_MINUTE -> EVERY_MINUTE

---

lib/openhab/triggers.py

i needed the previousState property to the ItemStateChangeTrigger.
for example:
```
lass rule_automate_ventilation_new(SimpleRule):
def __init__(self):
self.triggers = [ 
StartupTrigger(),                                                               # Run on startup to initialize, will reset the timer(!)
ItemCommandTrigger("timer_rule_automate_ventilation_new_init_hardware", command="OFF"),                       # GUI instellingen      
ItemCommandTrigger("number_ventilator_level_set_manual"),                       # GUI instellingen      
ItemStateChangeTrigger("switch_ventilator_level_toggle_auto",state="ON", previousState="OFF"),      # Manual mode gaat uit na 20 minuten
ItemStateChangeTrigger("humid_status_badkamer_sensor")                          # luchtvochtigheid verandert in …
```

ItemStateChangeTrigger has previousState property and moved ChannelEventTrigger up

---

README.md

ESH PR #[5953](https://github.com/eclipse/smarthome/pull/5953) is currently in the OH snapshots since ~1319.

Update README.md to include changes from ESH PR #5953

---

automation/lib/python/openhab/triggers.py

There are two undocumented ways to quickly created triggers using the when decorator. This is just a short form similar to what was used with the old item_triggered decorator, and I carried it over into the when decorator.  The cron one broke after the recent refactor of the trigger validation in the when decorator, but this PR makes it work again.
Cron:
```
@rule("Cron: simple trigger")
@when("0 0 7 * * ?")
def testSimpleCron(event):
```
And 'Item `<item>` changed':
```
@rule("Item: simple trigger")
@when("Test_Switch_1")
def testSimpleItem(event):
```

Corrected cron issue with simple rule trigger

---

automation/lib/python/openhab/items.py

I reworked lib/python/openhab/items.py to use a more generalized method for creating new objects, in particular the reworked items.add() method allows for creation of GroupItems with full support for group base item types and group functions.

Reworked items.add() to use builder style item creation

---

Docker/Dockerfile
Docker/cont-init.d/00-jython_initialize.sh
Docs/Docker.md

I'm very thankful for your work, these scripts are both good examples how to convert rules to Python, as well as make life easier. Since getting jython to run takes quite a lot of steps, I've decided to create a Dockerfile which will install Jython with all needed environment variables onto official Docker image of Openhab. 
Image was tested on debian version of amd64 and armhf flavours with M4, M5 and M6 images. It requires recent addition to official images which is a directory with scripts run on each startup. On each startup, it will enable experimental rule engine addon in addons.cfg and append python options to EXTRA_JAVA_OPTS.
openhab2-jython is not installed via dockerfile because, probably everybody will want to have their version in container's volumes for easier editing. One …

Dockerfile

---

Core/automation/lib/python/core/items.py

I have created this PR to update core/items.py to use the newItemBuilder() method of the ItemBuilderFactory service rather than the deprecated itemRegistry.newItemBuilder() method.
I have tested it on my installation and it is working without the deprecation warnings.

Updated core/items.py to use ItemBuilderFactory service

---

Docs/But-How-Do-I...-?.md

Fixes #56. The is a new `Things` action, that can be accessed with...
```
from core.actions import Things
log.debug("Test [{}]".format(Things.getThingStatusInfo("kodi:kodi:familyroom")))
```
[There is also a new `actions`](https://github.com/eclipse/smarthome/blob/master/bundles/automation/org.eclipse.smarthome.automation.module.script.defaultscope/src/main/java/org/eclipse/smarthome/automation/module/script/defaultscope/internal/DefaultScriptScopeProvider.java#L207) included in the default scope, that I will submit an ESH PR to rename to `thingactions`, so that the `core.actions` module does not get stepped on.

Update documentation for change to Thing actions

---

Core/automation/jsr223/core/components/200_JythonItemChannelLinkProvider.py
Core/automation/jsr223/core/components/200_JythonItemProvider.py
Core/automation/lib/python/core/items.py
Core/automation/lib/python/core/links.py
Core/automation/lib/python/core/log.py
Docs/Component-Scripts.md
Docs/Jython-Modules.md

This will introduce a breaking change for items.py. There is some namespace conflict with the default scope, but I think we can work around that. But the ItemChannelLinkProvider is needed for removing Items, since the links need to be removed before the Item can be removed. When I also added links.py, it was getting messing having core.items.add and core.links.add, so I renamed them to core.items.add_item and core.links.add_link (same for remove). Take a look at the Community OWM script to see some links.py usage. This PR is needed to get it working..
I was also getting exception when removing Items that hadn't gone through the JythonItemProvider, and I think I got that working now. 
There were some missing {} in log.py, preventing exceptions from being logged properly. This will …

Refactor items.py and provider, and add links.py and provider, and small fix to log.py

---

Community/OpenWeatherMap/automation/jsr223/community/openweathermap/owm_daily_forecast.py

Unmanaged OWM Things configured like:
```
Bridge openweathermap:weather-api:api "OpenWeatherMap Account" [apikey="abc", refreshInterval=30, language="de"] {
Thing weather-and-forecast hinckley "Local Weather And Forecast" [location="51.0000, 6.0000", forecastHours=120, forecastDays=0]
}
```
... have a Weather and Forecast ThingUID like:
```
openweathermap:weather-and-forecast:api:hinckley
```
But, a managed Weather and Forecast Thing has a ThingUID like:
```
openweathermap:weather-and-forecast:hinckley
```
I can't explain this yet, but it was breaking the rule due to an unexpected segment. Previously, I was getting the ThingID and appending it to `openweathermap:weather-and-forecast`. This PR scraps the use of ThingID, and just uses the ThingUID.

Use ThingUID instead of ThingID

---

Core/automation/lib/python/core/items.py

Changed default value of tags from `None` (not iterable) to `list()` (iterable).

Fix exception that occurred when tags parameter is not supplied to add_items()

---

Community/OpenWeatherMap/automation/jsr223/community/openweathermap/owm_daily_forecast.py

* Restructured how the rule is created
* Fixed SCALE transformation install
* Fixed Item existence check
* Changed to using values of Timestamp Items for calculating the number of remaining forecasts, and the Item label times
* Added group label changes to reflect current day of week
* Changed Item label to use time from Timestamp Items
* Added IconID
* Added manual group aggregation for Condition, ConditionID, Icon, IconID, and WindDirection

Group aggregation refactor

---

Core/automation/lib/python/core/date.py

Migrate to using ZonedDateTime from java.time, joda and java.util datetimes are depreciated. Added timezone support. Added simpler formatter with default matching OH default formatting. Added days, hours, minutes, seconds between functions. Added `__all__` import list to limit overlap when using wildcard imports on this module

[core.date] migrate Calendar to ZonedDateTime and add some new functionality

---

Core/automation/lib/python/core/utils.py

See: https://github.com/OH-Jython-Scripters/openhab2-jython/issues/98

[utils] The full item object is logged instead of the item's name

---

Core/automation/lib/python/core/date.py

The days_between function provides a result based on 24 hour intervals. I've added a calendar_days parameter so that you can specify if you'd like the result to return calendar days.
Resolves #107

[date] Added calendar_days parameter

---

Core/automation/lib/python/core/items.py

ManagedItemProvider.remove() takes a string, not an item.

Fix remove_item

---

Core/automation/jsr223/groovy/personal/README.md
Core/automation/jsr223/javascript/personal/README.md
Core/automation/jsr223/python/personal/README.md
Core/automation/lib/groovy/personal/README.md
Core/automation/lib/javascript/personal/README.md

These were missed in #94 due to the gitignore file.

Add personal directories

---

Community/IdeAlarm/automation/lib/python/community/idealarm/__init__.py

Removed the statement `self.log.debug('ideAlarm configuration was reloaded')` that must have been a left over from recent manoeuvres in the dark.

Removed faulty logging statement

---

Sphinx/Guides/Actions.rst
Sphinx/Guides/Event Object Attributes.rst
Sphinx/Guides/Logging.rst
Sphinx/Guides/Rules.rst
Sphinx/Guides/Triggers.rst

This pull request corrects formatting to render some hyperlinks, fixes some typographical / grammatical errors, and uses the RFC 2606 reserved domain name "example.com".

Correcting hyperlinks, typos, grammar, and example domain

---

Core/automation/lib/python/core/items.py
Core/automation/lib/python/core/links.py
Core/automation/lib/python/core/utils.py

These functions are useful in other modules, so it is best to have them in core.utils. I also changed core.links to use ManagedItemChannelLinkProvider so that links would persist after an OH restart. At some point, I will look at JythonItemProvider and JythonChannelLinkProvider to see if they couldn't be managed providers.

Moved validate_item and validate_channel from core.links to core.utils

---

Core/automation/lib/javascript/core/osgi.js

@lewie, would you like to review this one? I did my testing several months ago and I'm just getting around to committing now that the JS libraries are migrated. This should help a LOT in expanding the JS libraries.

Add an osgi.js library

---

Core/automation/lib/javascript/core/osgi.js

@lewie, it didn't look necessary, but I added this because it looked like a nice design pattern to follow for the JS libraries. I've used this in metadata.js too. WDYT?

Use self-executing anonymous function in osgi.js

---

Core/automation/lib/javascript/core/utils.js

This adds backwards compatibility to core.utils for OH 2.4. There are some other classes that worry me, but they will get cleaned up as the libraries get built out.

JS backwards compatibility

---

Core/automation/lib/javascript/core/metadata.js

JS library for manipulating Item metadata. I used this script for testing... [metadata_test.js.txt](https://github.com/openhab-scripters/openhab-helper-libraries/files/3329427/metadata_test.js.txt). I've been using snake_case in the JS libraries... will that be a problem? My reasoning was to keep things consistent with Jython.

Add metadata.js

---

Sphinx/conf.py

Fixes incorrect `html_baseurl` in `Sphinx/conf.py`. GH Pages will also stop complaining about an unacceptable/invalid CNAME, as this value is used for that as well.
Signed-off-by: Michael Murton <6764025+CrazyIvan359@users.noreply.github.com>

Fix incorrect baseurl and CNAME

---

Core/automation/lib/python/core/triggers.py
Core/automation/lib/python/core/utils.py
Sphinx/Guides/Triggers.rst
Sphinx/Python/Core/Packages and Modules/utils.rst

1. added ThingStatusUpdateTrigger and ThingStatusChangeTrigger to core.triggers and core.triggers.when decorator (https://github.com/openhab/openhab-core/pull/911)
2. removed event_type and trigger_name parameters from core.triggers.when
3. Removed reference to the simple when decorator formats. They should work now, but let's not promote them so that they can be removed in the future.
4. DirectoryEventTrigger, ItemAddedTrigger, ItemRemovedTrigger and ItemUpdatedTrigger have not worked for a long time and I'm close, but more work needs to be done to OSGIEventTrigger for them to work properly. This PR adds them to the core.triggers.when decorator.
5. Made some fixes to core.utils.validate_uid and changed core.triggers to use it in all of the trigger classes for generating the trigger name. …

Add thing status triggers

---

Core/automation/lib/python/core/triggers.py
Sphinx/Guides/Triggers.rst

This PR also removed the parameters from the core.triggers.when, since they were unnecessary.

Make Thing triggers backwards compatible

---

Core/automation/lib/python/core/date.py

I've added a function for turning seconds into a human readable string. I debated whether to put this into core.utils or core.date, but chose the latter since it's related to time. I also made corrections to a lot of the docstrings.

[date] Add human readable seconds

---

Community/Area Triggers and Actions/automation/jsr223/python/community/area_triggers_and_actions/area_triggers.py
Community/Area Triggers and Actions/automation/jsr223/python/personal/area_triggers_and_actions/update_metadata.py.example
Community/Area Triggers and Actions/automation/lib/python/community/area_triggers_and_actions/__init__.py
Community/Area Triggers and Actions/automation/lib/python/community/area_triggers_and_actions/area_actions.py
Community/Area Triggers and Actions/automation/lib/python/configuration.py.example
Community/Area Triggers and Actions/automation/lib/python/personal/area_triggers_and_actions/area_actions.py.example

These changes allow you to set default high and low brightness/color settings. For example, when an area is active, but the lux is higher than the lux_trigger, you can set the light to be set to a brightness level. Previously, the only option was to turn it off. There is now an option for high/lox lux for when an area is active and inactive.
There were also changes to the names used in settings, so users upgrading should review all of the changes. Documentation updates to follow.

Add high/low lux settings

---

Core/automation/lib/python/core/triggers.py

```
@when("Item added")
@when("Item removed")
@when("Item updated")
@when("Thing added")
@when("Thing removed")
@when("Thing updated")
@when("Directory /opt/test [created, deleted, modified]")# requires S1566, 2.5M2 or newer
@when("Subdirectory 'C:\My Stuff' [created]")# requires S1566, 2.5M2 or newer
```
One of the cool bits here is to be able to reload a rule using another rule when an Item or Thing is added/removed. Something like...
```
from core.rules import rule
from core.triggers import when
def zwave_thing_trigger_generator():
def generated_triggers(function):
for thing_uid in [thing.UID.toString() for thing in things.all if "zwave" in thing.UID.toString()]:
when("Thing {} changed".format(thing_uid))(function)
return function
return generated_triggers
@rule("Z-Wave Thing added or …
```

Add Items, Things, and Directories
