openhab-scripters/openhab-helper-libraries

README.md, lib/openhab/triggers.py, scripts/examples/channel_event_example.py
This change adds the ChannelEventTrigger.
=> ChannelEventTrigger added

Script Examples/000_HelloWorld.py, Script Examples/README.md, automation/jsr223/000_components/README.md, automation/lib/python/openhab/README.md, automation/lib/python/openhab/rules.py
=> Fixed issue using the rule decorator with class and several examples

Docker.md, README.md
I was personally keen to see this in action, so have outlined the final steps to get this going in a Docker image - it took a bit of trial and error to get it right. Hopefully it'll be of value to others as well.
=> Steps to run jython in Docker

README.md
A couple of minor edits of things I found and have tried to fix. Not 100% sure it's the best way, so if you can review that would be great.
Also, It would be great if you were able to turn on the Wiki on the repo, that way people could put up examples etc is a much more casual way (or if there is a better place, maybe put up with Wiki read-only and link to it there).
Thanks again for your work on this, it's great - Python is soooo much better than Xbase! :)
=> Minor documentation edits - Please Review

automation/lib/python/openhab/triggers.py
I've tested this, but there are so many combinations of rule triggers that I couldn't test all of them.
=> Refactored @when decorator and corrected 'changed from' trigger_type

automation/lib/python/openhab/rules.py
Tags can be added to a rule like this...
@rule("Test tags", tags=["Tag1", "Tag2"])
=> Added tags parameter to rule decorator

Community/OpenWeatherMap/automation/jsr223/community/openweathermap/owm_daily_forecast.py, Docs/Community.md
With #63, I've made changes to the Community OWM script to resolve an issue where Items were not linking properly.
=> Fix for Items not linking

Community/OpenWeatherMap/automation/jsr223/community/openweathermap/owm_daily_forecast.py
Previously there was just a Forecast_Temperature_X group. I've replaced this with Forecast_Temperature_High_X and Forecast_Temperature_Low_X groups.
=> Added high and low temperature forecast groups

Docs/Defining-Rules.md
ItemStateUpdateTrigger was imported, but  ItemStateChangeTrigger is used.
=> Fixed error in example code

Community/OpenWeatherMap/automation/jsr223/community/openweathermap/owm_daily_forecast.py
This verification will prevent the script from running if the Thing is not configure properly. I could reconfigure it, but that seemed too invasive, so there is just a log to warn the user.
=> [OWM} Added verification for forecastHours and forecastDays

Docs/Jython-Modules.md
Here we go, docs with clean commit history.
Rebasing would be the right way to do it, but I ended up having to delete my fork and make a new one because of my previous attempt to merge your upstream repo.
=> Documentation for date upgrades

Core/automation/lib/python/core/date.py
There were a lot of methods that were missing ().
=> [core.date] Fixed lots of missing ()

Script Examples/hello_world.py
=> Fixed some broken examples in hello_world.py

Script Examples/hello_world.py
=> [hello_world] Corrected typo in comment

Docs/Getting-Started.md
=> Updated logging location

Docs/Getting-Started.md
Reverts OH-Jython-Scripters/openhab2-jython#101
=> Revert "Updated logging location"

Docs/Getting-Started.md
=> Update logging information

Script Examples/hello_world.py
=> Fixed typo

Script Examples/timer_example.py
=> Fix typo and minor cleanup

Core/automation/lib/python/core/items.py
=> Add ManagedItemProvider

Core/automation/lib/python/core/rules.py
This was previously added and lost after the openhab->core directory restructuring.
=> Readd rule UID

Docs/README.md
=> Python (Jython)->Jython (Python)

Core/automation/lib/python/core/actions.py
Some of the Core Actions were missing, so I've added Ping, Exec, HTTP and LogAction.
=> [actions] Add missing Core Actions

Docs/Python/But-How-Do-I.md, Script Examples/Python/timer_example.py
=> Add documentation for new actions

Core/automation/lib/python/core/actions.py
Added another Action that was missing.
=> Add ScriptExecution Action

Core/automation/jsr223/python/core/components/200_JythonBindingInfoProvider.py, Core/automation/jsr223/python/core/components/200_JythonExtensionProvider.py, Core/automation/jsr223/python/core/components/200_JythonItemChannelLinkProvider.py, Core/automation/jsr223/python/core/components/200_JythonItemProvider.py, Core/automation/jsr223/python/core/components/200_JythonThingProvider.py, Core/automation/jsr223/python/core/components/200_JythonThingTypeProvider.py, Core/automation/jsr223/python/core/components/200_JythonTransform.py
I left out the core.osgi import when cleaning these up for #109.
=> Fix component scripts

Script Examples/Python/hello_world.py
=> Fix loggers in hello_world.py

Docs/Python/Defining-Rules.md, Docs/Python/Event-Object-Attributes.md, Docs/Python/Jython-Modules.md, Docs/Python/README.md
=> Document requirements for System Started trigger

.github/ISSUE_TEMPLATE/groovy_bug_report.md, .github/ISSUE_TEMPLATE/groovy_feature_request.md, .github/ISSUE_TEMPLATE/javascript_bug_report.md, .github/ISSUE_TEMPLATE/javascript_feature_request.md, .github/ISSUE_TEMPLATE/jython_bug_report.md, .github/ISSUE_TEMPLATE/jython_feature_request.md
=> Add bug report and feature request templates for Groovy and Javascript

.github/ISSUE_TEMPLATE/groovy_bug_report.md, .github/ISSUE_TEMPLATE/groovy_feature_request.md, .github/ISSUE_TEMPLATE/javascript_bug_report.md, .github/ISSUE_TEMPLATE/javascript_feature_request.md, .github/ISSUE_TEMPLATE/jython_bug_report.md, .github/ISSUE_TEMPLATE/jython_feature_request.md
=> Fix names in templates

.github/ISSUE_TEMPLATE/groovy_bug_report.md, .github/ISSUE_TEMPLATE/groovy_feature_request.md, .github/ISSUE_TEMPLATE/javascript_bug_report.md, .github/ISSUE_TEMPLATE/javascript_feature_request.md, .github/ISSUE_TEMPLATE/jython_bug_report.md, .github/ISSUE_TEMPLATE/jython_feature_request.md
=> Fix names in templates again

Docs/Javascript/README.md
=> Correct file locations in JS README

Docs/Javascript/README.md
=> [javascript] Removed another reference to JSRule.js in README

Core/automation/lib/python/core/date.py
=> [date] Use getID() instead of getId()

Core/automation/lib/python/core/triggers.py
Triggers for StringItems that used a new_state or old_state could have invalid characters for the Trigger UUIDs, which was raising an exception in the validation. This PR corrects that, and also allows for states and Channel triggers with spaces in them. While working this PR, I could see extreme edge cases where the Trigger UUIDs were not unique and the Triggers would overwrite themselves. To prevent this, all Trigger names now have generated UUIDs appended to them. 
You can specify a StringItem's state with the following formats. This is only necessary if the state or Channel trigger has spaces in it.
@when("Item Virtual_String_1 changed from 'this is a test' to 'this is another test'")
@when("Item Virtual_String_1 changed from \"this is a test\" to \"this is another test\"") …
=> Fix string triggers and UUIDs

Sphinx/conf.py
=> Fix 'Edit on GH' footer link

Core/automation/lib/python/core/date.py, Design Patterns/Mode (Time of Day)/automation/jsr223/python/personal/mode_example.py, Sphinx/Examples/Design Patterns/Design Patterns.rst
=> Minor doc tweaks and corrections

Script Examples/Python/testing_example.py
=> Add scriptLoaded

Design Patterns/Mode (Time of Day)/automation/jsr223/python/personal/mode_example.py, Sphinx/Examples/Design Patterns/Design Patterns.rst, Sphinx/Examples/Design Patterns/Mode (Time of Day).rst
=> Update documentation for mode_example

Core/automation/lib/groovy/configuration.groovy.example, Core/automation/lib/javascript/configuration.js.example
=> Add content to JS and Groovy config example files

Sphinx/Guides/Rules.rst, Sphinx/Python/Reference.rst
=> Added a Scripts vs Modules section to doc

Community/OpenWeatherMap/automation/jsr223/python/community/openweathermap/owm_daily_forecast.py
Fixed Cloudiness and Humidity units and group function (no more unit of 'one'!).
=> Fix group functions in owm_daily_forecast.py

Community/OpenWeatherMap/automation/jsr223/python/community/openweathermap/owm_daily_forecast.py
=> Added parameter to scriptLoaded

Core/automation/lib/python/core/items.py, Core/automation/lib/python/core/log.py, Core/automation/lib/python/core/rules.py, Core/automation/lib/python/core/triggers.py, Core/automation/lib/python/core/utils.py
1) Minor logging improvements
2) Improved handling of triggers that do not pass validation check. I decided not to load rules if there is a bad trigger definition. Scripts will now continue to load if there is a rule with a bad trigger definition.
3) Moved the trigger UID function from core.triggers to core.utils and improved it a bit.
=> Improved logging

Core/automation/lib/python/core/jsr223.py
=> Minor formatting change

Core/automation/lib/python/core/log.py
=> Update docstrings in core.log

Script Examples/Python/hello_world.py
=> Updated comment in hello_world

Core/automation/lib/javascript/core/osgi.js
This fixes some errors I found when using find_services.
=> [osgi] Use null rather than undefined

Core/automation/jsr223/python/core/components/100_OsgiEventTrigger.py, Core/automation/lib/python/core/metadata.py, Core/automation/lib/python/core/triggers.py, Core/automation/lib/python/core/utils.py, Sphinx/Guides/But How Do I.rst, Sphinx/Guides/Triggers.rst, Sphinx/Python/Core/Packages and Modules/utils.rst, Sphinx/Python/Reference.rst
Previously, the access to metadata was flat and you could only navigate the top level. This PR allows you to now access nested dicts with the metadata's configuration. Details in docstrings.
=> [metadata] Added concept of key hierarchies

Core/automation/jsr223/python/core/components/100_OsgiEventTrigger.py, Core/automation/lib/python/core/metadata.py, Core/automation/lib/python/core/triggers.py, Core/automation/lib/python/core/utils.py, Sphinx/Guides/But How Do I.rst, Sphinx/Guides/Triggers.rst, Sphinx/Python/Core/Packages and Modules/utils.rst, Sphinx/Python/Reference.rst
Reverts openhab-scripters/openhab-helper-libraries#204. Accidently included changes for another commit.
=> Revert "[metadata] Added concept of key hierarchies"

Core/automation/lib/python/core/metadata.py
Adding these changes in again...
=> [metadata] Add key hierarchy (take 3)

Core/automation/lib/javascript/core/actions.js, Sphinx/Guides/Actions.rst, Sphinx/Guides/Logging.rst
Some of the existing libraries could be changed to use this, but I think it would be better to address that once more of the libraries have been built out.
=> Add core.actions.js

Sphinx/Python/Reference.rst
=> Updates to Python/Reference.rst

Sphinx/Examples/Action Example.rst, Sphinx/Examples/Channel Event Example.rst, Sphinx/Examples/Directory Watcher Example.rst, Sphinx/Examples/Extension Provider Usage Example.rst, Sphinx/Examples/Hello World.rst, Sphinx/Examples/Rule Registry Example.rst, Sphinx/Examples/Testing Example.rst, Sphinx/Examples/Timer Example.rst, Sphinx/Guides/But How Do I.rst
* Switch Examples pages to use `literalinclude` of script file instead of import.
* Add post ESH-Merge safe imports to some examples in `But How Do I...?`
Signed-off-by: Michael Murton <6764025+CrazyIvan359@users.noreply.github.com>
=> Updates to Examples and But How Do I pages

Community/ideAlarm/automation/lib/python/community/idealarm/__init__.py, Core/automation/lib/python/core/utils.py, Script Examples/Python/testing_example.py
=> Change the names of the "check first" functions

Sphinx/Getting Started/Installation.rst, Sphinx/Guides/But How Do I.rst, Sphinx/Python/Community/ideAlarm/Installation.rst
=> Fix broken doc links

Community/Alexa Speak and Respond/automation/jsr223/python/personal/speak_and_respond/speak_and_respond.py.example, Sphinx/Python/Community/Alexa Speak and Respond.rst, Sphinx/Python/Examples.rst, Sphinx/Python/Examples/Alexa Speak and Respond.rst
=> Move speak_and_respond from Script Examples to Community

Sphinx/Guides/Metadata.rst, Sphinx/Python/Core/Packages and Modules/metadata.rst, Sphinx/index.rst
=> Update metadata docs

Sphinx/Guides/Actions.rst, Sphinx/Python/Core/Packages and Modules/actions.rst
=> Update actions docs

Community/Delete and Rediscover Z-Wave Things/automation/jsr223/python/community/delete_zwave_things/delete_zwave_things.py
... and the Delete_Zwave_Things Item is now created and autoupdate is set to false.
=> [speak_and_respond] Use core.actions for Exec

Sphinx/Python/Community/Alexa Speak and Respond.rst
=> [speak_and_respond] Update documentation

Community/Esper/automation/jsr223/python/community/esper/components/000_Esper.py, Community/Esper/automation/jsr223/python/community/esper/esper.py.example, Community/Esper/automation/lib/python/community/esper/__init__.py
=> [esper] Python3 compatibility required for Sphinx

Community/Mode (Time of Day)/automation/jsr223/python/community/update_mode/update_mode.py, Community/Mode (Time of Day)/automation/lib/python/configuration.py.example
=> [mode] Switch to lowercase variables and update docs

Community/Sonos/automation/jsr223/python/personal/sonos/greeting.py.example, Community/Sonos/automation/jsr223/python/personal/sonos/tts.py.example, Community/Sonos/automation/lib/python/community/sonos/playSound.py, Community/Sonos/automation/lib/python/community/sonos/speak.py
=> [sonos] Move examples to personal

Community/WeatherStationUploader/automation/lib/python/configuration.py.example
This change is required to resolve errors in the Sphinx documentation.
=> [weatherStationUploader] Change logLevel to string

Core/automation/lib/python/core/date.py
=> [date] Round seconds in human_readable_seconds and update docs

Core/automation/lib/python/core/items.py
=> [items] Change jsr223.scope import, add __all__, and update docs

Core/automation/lib/python/core/links.py
=> [links] Change jsr223.scope import, add __all__, and update docs

Core/automation/lib/python/core/rules.py
=> [rules] Change jsr223.scope import, add __all__, and update docs

Core/automation/lib/python/core/utils.py
I also added the ability to use a string or Item for some functions, and snake_cased some parameters.
=> [utils] Change jsr223.scope import, add __all__, and update docs

Core/automation/lib/python/core/osgi/__init__.py, Core/automation/lib/python/core/osgi/events.py
I also added some missing returns.
=> [osgi] Change jsr223.scope import and update docs

Sphinx/build-docs.sh, Sphinx/conf.py
=> Updated the docs build script

Core/automation/lib/python/core/osgi/events.py
core.osgi.events.OsgiEventTrigger has not yet been migrated to the newer automation API using TriggerBuilder. This begins the move, but the 100_OsgiEventTrigger.py component script will also need updating. I will include that in a future PR, along with changes to core.triggers to fix ItemRegistryEventTrigger and DirectoryEventTrigger and utilize them in `when`. There may be a better way to implement some of these triggers though, using ItemAddedEvent and ItemUpdatedEvent.
This PR also fixes the imports that inadvertently got messed up in #250 .
=> [events] Fix imports and start API update

Community/AutoRemote/automation/lib/python/community/autoremote/__init__.py
As requested in #231, [autoremote] Needs some docs. Would this work as a starter?
=> Added AutoRemote usage description

Community/AutoRemote/automation/lib/python/community/autoremote/__init__.py
=> [autoremote] Corrected punctuation

Community/Mode (Time of Day)/automation/jsr223/python/community/update_mode/update_mode.py
=> [mode] Fixed modes triggered by Channels

Sphinx/Python/Reference.rst
=> Added some suggested reading links

Sphinx/Guides/But How Do I.rst, Sphinx/Guides/Rules.rst
=> Documentation updates

Sphinx/Guides/Actions.rst
Added Pushover and Pushbullet actions information for Jython.
Signed-off-by: Brent Barrand <bigredbrent@gmail.com>
=> Pushover and Pushbullet actions for Jython

Sphinx/Guides/Actions.rst
UpdateActions.str to reflect new mail binding action
Signed-off-by: Vincent Regaud <vzorglub@gmail.com>
=> UpdateActions.rst to reflect 2.x mail binding action

Sphinx/Contributing/Writing Docs.rst, Sphinx/Getting Started/Docker.rst
Small fixes to the documentation that I noticed while trying to add Jython support to a Docker install.
=> Docker doc update

Core/automation/lib/python/core/utils.py
=> [core.utils] Add comma to __all__

Community/NOAA Weather Alerts/automation/jsr223/python/personal/nws_alerts/nws_alerts.py, Sphinx/Python/Community/NOAA Weather Alert.rst
=> Add nws_alerts

Community/TTS (flite)/automation/lib/python/community/flite_tts/__init__.py, Community/TTS (flite)/automation/lib/python/configuration.py.example, Sphinx/Python/Community/TTS (flite).rst
=> Add TTS (flite)

Sphinx/Python/Community/NOAA Weather Alert.rst
=> Fix mws_alert doc header

Community/Trash alert (Netherlands)/automation/jsr223/python/community/trash_alert/trash_alert.py, Sphinx/Python/Community/Trash alert (Netherlands).rst
=> Add Trash Alert (Netherlands)

Script Examples/Python/script_extension_example.py, Sphinx/Examples/ScriptExtension Example.rst
=> Add script extension example

Script Examples/Python/reschedulable_cron_example.py, Sphinx/Examples/Reschedulable Cron Example.rst
=> Add reschedulable cron example

Core/automation/jsr223/python/core/000_startup.py
=> Add a python startup info script

Core/automation/jsr223/python/core/components/100_OsgiEventTrigger.py, Core/automation/lib/python/core/osgi/events.py
=> Pylint changes for core.osgi.events

Core/automation/jsr223/python/core/000_startup.py
=> Better detail for 000_startup.py

Community/Alexa Speak and Respond/automation/jsr223/python/personal/speak_and_respond/speak_and_respond.py.example
=> Update speak_and_respond example

Community/Delete and Rediscover Z-Wave Things/automation/jsr223/python/community/delete_zwave_things/delete_zwave_things.py, Community/OpenWeatherMap/automation/jsr223/python/community/openweathermap/owm_daily_forecast.py, Community/TTS (flite)/automation/lib/python/community/flite_tts/__init__.py, Community/Trash alert (Netherlands)/automation/jsr223/python/community/trash_alert/trash_alert.py, Community/WeatherStationUploader/automation/jsr223/python/community/weatherstationuploader/weatherStationUploader.py
=> Improve logging and add some unicode

Community/Mode (Time of Day)/automation/jsr223/python/community/update_mode/update_mode.py, Community/Mode (Time of Day)/automation/lib/python/configuration.py.example
Names of settings have changed, so review all settings if upgrading. Documentation to follow.
=> [update_mode] Add day of the week

Core/automation/jsr223/python/core/000_Startup.py
... and added a check for configuration.py.
=> Renamed 000_startup.py

Core/automation/jsr223/python/core/components/100_StartupTrigger.py
=> Pylint changes for 100_StartupTrigger.py

Core/automation/jsr223/python/core/components/100_DirectoryTrigger.py
=> Fix DirectoryEventTrigger

Core/automation/lib/python/core/actions.py
=> Add OH ActionService

Core/automation/lib/python/core/date.py, Core/automation/lib/python/core/jsr223.py, Core/automation/lib/python/core/metadata.py, Core/automation/lib/python/core/osgi/__init__.py, Core/automation/lib/python/core/osgi/events.py, Core/automation/lib/python/core/utils.py
=> Misc cleanup and fixes

Core/automation/lib/python/core/log.py, Core/automation/lib/python/core/rules.py
Makes the configuration.py optional, improves logging of exceptions, and cleans some things up.
=> Fix log_traceback and make configuration optional

Community/Area Triggers and Actions/automation/jsr223/python/community/area_triggers_and_actions/area_triggers.py, Community/Area Triggers and Actions/automation/lib/python/community/area_triggers_and_actions/area_actions.py, Community/Area Triggers and Actions/automation/lib/python/configuration.py.example
The mode Item and the brightness level that disables area actions are now configurable.
=> [area_triggers] Made things more configurable
